<?php
    session_start();
    session_regenerate_id(true);
    unset($_SESSION['email']);
    unset($_SESSION['id']);
    unset($_SESSION['name']);
    unset($_SESSION['mobile']);
    unset($_SESSION['status']);
    session_destroy();
    header('location:login.php');
?>  